default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  username: admin
  password: admin
  port: 5434

#port: 5432

test:
  <<: *default
  database: app_test
  username: admin
  password: admin
  port: 5434

production:
  <<: *default
  database: blog--spletniki_production
  username: blog--spletniki
  password: <%= ENV['BLOG--SPLETNIKI_DATABASE_PASSWORD'] %>